linters:
  enable-all: true
  disable:
    - dupl
    - wrapcheck
    - forbidigo
    - funlen
    - gocognit
    - varnamelen
    - cyclop
    - gochecknoglobals
    - exhaustruct
    - lll
    - depguard
